---

# This docker compose script creates a mongo DB instance available on localhost:27017.
# For viewing mongo-express, go to localhost:8081.
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
