repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        files: scheduler
    -   id: end-of-file-fixer
        files: scheduler
    -   id: trailing-whitespace
        files: scheduler
-   repo: local
    hooks:
    -   id: black
        files: scheduler
        name: black
        entry: bash -c 'cd scheduler && poetry run black'
        language: system
        types: [python]
    -   id: flake8
        files: scheduler
        name: flake8
        entry: bash -c 'cd scheduler && poetry run flake8'
        language: system
        types: [python]
