db:
  url: "mongodb://localhost:27017/development"

kafka:
  broker:
    url: "localhost:9092"
  topic: "card"

NODE_ENV: "development"

card-watch-list:
  redis:
    port: 6379
    host: "localhost"

user-repository:
  redis:
    port: 6380
    host: "localhost"

json-web-token:
  secret: "4KZ2IsFnZhqNDjO0WcXla_6WwioKKhXabalggWLl"
